apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-base-image: ${region}-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python310
    run.googleapis.com/build-enable-automatic-updates: 'true'
    run.googleapis.com/build-function-target: realh_capital_evening_can_slim_scout_job
    run.googleapis.com/build-image-uri: ${region}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/realh-capital-evening-can-slim-scout-job:latest
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal
    run.googleapis.com/maxScale: '1'
  labels:
    cloud.googleapis.com/location: ${region}
  name: realh-capital-evening-can-slim-scout-job
  namespace: '${PROJECT_NUMBER}'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/base-images: '{"realh-capital-evening-can-slim-scout-job-1":"${region}.pkg.dev/serverless-runtimes/google-22/runtimes/python310"}'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - image: ${IMAGE_URL}
        name: realh-capital-evening-can-slim-scout-job-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      runtimeClassName: run.googleapis.com/linux-base-image-update
      serviceAccountName: ${REPLACE_WITH_SERVICE_ACCOUNT}
      timeoutSeconds: 540
  traffic:
  - latestRevision: true
    percent: 100
